### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by Quadsam** [JohnathanLP/cppadventuregroup#1]
How do you install atom for raspberry pi 3 model B
I've tried 
`sudo apt-get install atom`
and got the error
`E: Unable to locate package atom`
i also tried
`sudo add-apt-repository ppa:webupd8team/atom`
and got
`sudo: add-apt-repository: command not found`
then i tried
`sudo wget https://atom.io/download/deb -O atom.deb`
this worked so i ran the following code after
`sudo dpkg -i atom.deb`
and got
`dpkg: error processing archive atom.deb (--install):`
` package architecture (amd64) does not match system (armhf)`
`Errors were encountered while processing:`
 `atom.deb`
can you please help me

**Comment by JohnathanLP** [comment]
I will look at it some more when I get a chance, but it seems that there are a lot of problems with running Atom on Raspbian. I know I have done it on a Pi before, but it was a different operating system. For what you are doing, however, pretty much any text editor will work. Gedit and Geany are two examples that I know should work on Raspbian, they can be installed easily with 'sudo apt-get install gedit' and 'sudo apt-get install geany'.
