### ISSUE TITLE
Raspberry Pi?

### ISSUE THREAD

**Issue by Quadsam** [JohnathanLP/cppadventuregroup#2]
i get this error when I try to run on raspbian

'main.cpp: In function ‘int main()’:
main.cpp:269:23: error: ‘to_string’ is not a member of ‘std’
   livesDisp.setString(std::to_string(lives));'

**Comment by JohnathanLP** [comment]
Try adding -std=c++14 to the end of your compile script.

**Comment by Quadsam** [comment]
thanks!! whats your email so I can email you with further questions?

**Comment by JohnathanLP** [comment]
Creating or commenting on issues here will actually send me an email automatically. :)

**Comment by Quadsam** [comment]
how do you comment?

**Comment by JohnathanLP** [comment]
You just did.

**Comment by Quadsam** [comment]
i thought this was an issue

**Comment by JohnathanLP** [comment]
Yes, I get an email whenever an issue is created, or whenever someone comments on an existing issue.

**Comment by JohnathanLP** [comment]
I'm also on GitHub for various stuff several times a week, and will see the notification.

**Comment by Quadsam** [comment]
I havent run my code in a while but when i did today i got this gigantic error

/tmp/ccSQuiBu.o: In function `main':
main.cpp:(.text+0x1124): undefined reference to `sf::SoundBuffer::SoundBuffer()'
main.cpp:(.text+0x1180): undefined reference to `sf::SoundBuffer::loadFromFile(std::string const&)'
main.cpp:(.text+0x11ec): undefined reference to `sf::Sound::Sound()'
main.cpp:(.text+0x120c): undefined reference to `sf::Sound::setBuffer(sf::SoundBuffer const&)'
main.cpp:(.text+0x1224): undefined reference to `sf::SoundSource::setPitch(float)'
main.cpp:(.text+0x1234): undefined reference to `sf::SoundBuffer::SoundBuffer()'
main.cpp:(.text+0x1288): undefined reference to `sf::SoundBuffer::loadFromFile(std::string const&)'
main.cpp:(.text+0x12f0): undefined reference to `sf::Sound::Sound()'
main.cpp:(.text+0x1310): undefined reference to `sf::Sound::setBuffer(sf::SoundBuffer const&)'
main.cpp:(.text+0x1328): undefined reference to `sf::Sound::setLoop(bool)'
main.cpp:(.text+0x139c): undefined reference to `sf::Sound::play()'
main.cpp:(.text+0x1b70): undefined reference to `sf::Sound::play()'
main.cpp:(.text+0x1b88): undefined reference to `sf::SoundSource::setPitch(float)'
main.cpp:(.text+0x1ff4): undefined reference to `sf::Sound::~Sound()'
main.cpp:(.text+0x2004): undefined reference to `sf::SoundBuffer::~SoundBuffer()'
main.cpp:(.text+0x2018): undefined reference to `sf::Sound::~Sound()'
main.cpp:(.text+0x2028): undefined reference to `sf::SoundBuffer::~SoundBuffer()'
main.cpp:(.text+0x2404): undefined reference to `sf::Sound::~Sound()'
main.cpp:(.text+0x2418): undefined reference to `sf::SoundBuffer::~SoundBuffer()'
main.cpp:(.text+0x2430): undefined reference to `sf::Sound::~Sound()'
main.cpp:(.text+0x2444): undefined reference to `sf::SoundBuffer::~SoundBuffer()'
collect2: error: ld returned 1 exit status
./linuxRun.sh: line 4: ./Lothoavudd: No such file or directory

My code is  [here](https://github.com/Samsung13M/cppgame)

**Comment by JohnathanLP** [comment]
All I can think is that it looks like you need to re-install SFML.
